apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lamadome/fake-service:latest
          env:
            - name: LISTEN_ADDR
              value: "0.0.0.0:9090"
            - name: NAME
              value: "backend"
          ports:
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
