#index: 7
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend.yaml
- virtualdestination-fake-backend.yaml
images:
- name: lamadome/fake-service
  newTag: 6dac2a0f3cb5
