apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fake-backend
  labels:
    app: backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
      version: v2
  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      containers:
        - name: backend
          image: lamadome/fake-service:latest
          env:
            - name: LISTEN_ADDR
              value: "0.0.0.0:9090"
            - name: NAME
              value: "backend-cluster1"
          ports:
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fake-backend
  labels:
    app: backend
    version: v2
spec:
  selector:
    app: backend
    version: v2
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
