apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: fake-service
  namespace: fake-frontend
spec:
  importFrom:
  - workspaces:
    - name: gateways
    resources:
    - kind: SERVICE
  exportTo:
  - workspaces:
    - name: gateways
    resources:
    - kind: SERVICE
      labels:
        app: frontend
    - kind: ALL
      labels:
        expose: "true"
