apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fake-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: lamadome/fake-service:latest
          env:
            - name: LISTEN_ADDR
              value: "0.0.0.0:8080"
            - name: NAME
              value: "frontend"
            - name: UPSTREAM_URIS
              value: "http://fake-backend.global:9090"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fake-frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
