apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend.yaml
  - backend.yaml
  - virtualdestination-fake-backend.yaml
  - virtualdestination-fake-frontend.yaml
  - routetable-fake-frontend.yaml
  - routetable-fake-backend.yaml
  - fake-service-workspace-settings.yaml
images:
  - name: lamadome/fake-service
    newTag: b65627580651fc650b03e47269916f06ed884ff4
patches:
  - patch: |-
      - op: replace
        path: /spec/http/0/forwardTo/destinations/0/weight
        value: 50
      - op: replace
        path: /spec/http/0/forwardTo/destinations/1/weight
        value: 50
    target:
      group: networking.gloo.solo.io
      kind: RouteTable
      name: fake-frontend
      version: v2
