#test
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend.yaml
- backend.yaml
- virtualdestination-fake-backend.yaml
- routetable-fake-frontend.yaml
- routetable-fake-backend.yaml
- fake-service-workspace-settings.yaml
images:
- name: lamadome/fake-service
  newTag: 058fb8557e675e02fa55e7ed4e4efec947d8f1a8
