apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: fake-backend
  namespace: fake-frontend
#  labels:
#    expose: "true"
spec:
  hosts:
    - backend.fake-backend
    - fake-backend.global
  workloadSelectors:
  - selector:
      labels:
        app: frontend
  http:
    - name: fake-backend
      matchers:
      - uri:
          prefix: /
      forwardTo:
        destinations:
          - ref:
              name: backend
              namespace: fake-backend
            kind: VIRTUAL_DESTINATION
            subset:
              version: v3
            port:
              number: 9090
