apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: fake-backend
  namespace: fake-frontend
#  labels:
#    expose: "true"
spec:
  hosts:
    - backend.fake-backend
    - fake-backend.global
  workloadSelectors:
  - selector:
      labels:
        app: frontend
  - selector:
      labels:
        app: backend
  http:
    - name: fake-backend-stable
      matchers:
      - uri:
          prefix: /
      forwardTo:
        destinations:
          - ref:
              name: backend
              namespace: fake-backend
            kind: SERVICE
            subset:
              version: stable
            port:
              number: 9090
            weight: 100
          - ref:
              name: backend
              namespace: fake-backend
            kind: SERVICE
            subset:
              version: canary
            port:
              number: 9090
            weight: 0
          
