apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: fake-backend
  namespace: fake-frontend
#  labels:
#    expose: "true"
spec:
  hosts:
    - backend.fake-backend
    - backend.global
  http:
    - name: fake-backend
      matchers:
      - uri:
          prefix: /
      forwardTo:
        destinations:
          - ref:
              name: backend
              namespace: fake-backend
            kind: VIRTUAL_DESTINATION
            port:
              number: 9090
