apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: fake-frontend
  namespace: fake-frontend
  labels:
    expose: "true"
spec:
  http:
    - name: fake-frontend
      matchers:
      - uri:
          exact: /fake
      forwardTo:
        destinations:
          - ref:
              name: frontend
              namespace: fake-frontend
            kind: VIRTUAL_DESTINATION
            port:
              number: 8080
