apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: frontend
  namespace: fake-frontend
  labels:
    expose: "true"
spec:
  hosts:
  - fake-frontend.global
  services:
  - namespace: fake-frontend
    labels:
      app: frontend
  ports:
    - number: 8080
      protocol: HTTP
