apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-canary
  namespace: fake-backend
  labels:
    app: backend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
      version: canary
  template:
    metadata:
      labels:
        app: backend
        version: canary
    spec:
      containers:
        - name: backend
          image: lamadome/fake-service:latest
          env:
            - name: LISTEN_ADDR
              value: "0.0.0.0:9090"
            - name: NAME
              value: "backend-cluster1-canary"
          ports:
            - containerPort: 9090
