#test
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-canary.yaml
images:
- name: lamadome/fake-service
  newTag: 524cdd8fae06008c4541bb40f0b1ca1ed603dc4447991a62e94600bbc38d2b7b