apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: main
  namespace: istio-gateways
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: north-south-gw
      namespace: istio-gateways
      cluster: cluster1
  workloadSelectors: []
  http:
    - name: fake
      matchers:
      - uri:
          exact: /
      delegate:
        routeTables:
          - labels:
              expose: "true"
#            workspace: fake-service
    - name: payments
      matchers:
        - uri:
            exact: /fake
      delegate:
        routeTables:
          - labels:
              expose-payments: "true"
