apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: main
  namespace: istio-gateways
spec:
  hosts:
    - '*'
  virtualGateways:
    - name: north-south-gw
      namespace: istio-gateways
      cluster: cluster1
  workloadSelectors: []
  http:
    - name: fake
      matchers:
      - uri:
          exact: /fake
      delegate:
        workspace: fake-service
        routeTables:
          - labels:
              expose: "true"
    - name: payments
      matchers:
        - uri:
            exact: /fake
      delegate:
        workspace: payments
        routeTables:
          - labels:
              expose: "true"
