apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gloo-agent
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - name: cluster1
        cluster: cluster1
      - name: cluster2
        cluster: cluster2
      - name: in-cluster
        cluster: in-cluster
      - name: mgmt
        cluster: mgmt
  template:
    metadata:
      name: 'gloo-agent-{{name}}'
    spec:
      project: gloo-mesh
      source:
        path: teams/platform/gloo-mesh-agent/{{name}}
        repoURL: 'https://github.com/lamadome/GlooOps-lamadome2'
        targetRevision: HEAD
      destination:
        name: '{{cluster}}'
        namespace: gloo-mesh
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: {}
