apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../mgmt/

patches:
  - target:
      kind: IstioLifecycleManager
      name: cluster-installation
    patch: |-
      - op: replace
        path: /metadata/name
        value: cluster2-installation
      - op: replace
        path: /spec/installations/0/clusters/0/name
        value: cluster2
      - op: replace
        path: /spec/installations/0/istioOperatorSpec/values/global/multiCluster/clusterName
        value: cluster2
      - op: replace
        path: /spec/installations/0/istioOperatorSpec/values/global/network
        value: cluster2
  - target:
      kind: GatewayLifecycleManager
      name: cluster-ingress
    patch: |-
      - op: replace
        path: /metadata/name
        value: cluster2-ingress
      - op: replace
        path: /spec/installations/0/clusters/0/name
        value: cluster2
  - target:
      kind: GatewayLifecycleManager
      name: cluster-eastwest
    patch: |-
      - op: replace
        path: /metadata/name
        value: cluster2-eastwest
      - op: replace
        path: /spec/installations/0/clusters/0/name
        value: cluster2
      - op: replace
        path: /spec/installations/0/istioOperatorSpec/components/ingressGateways/0/label/topology.istio.io~1network
        value: cluster2
      - op: replace
        path: /spec/installations/0/istioOperatorSpec/components/ingressGateways/0/k8s/env/1/value
        value: cluster2
