apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bookinfo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - List:
        elements:
          - name: cluster1
            cluster: cluster1
          - name: cluster2
            cluster: cluster2
          - name: mgmt
            cluster: in-cluster
  template:
    metadata:
      name: 'bookinfo-{{name}}'
    spec:
      project: bookinfo
      source:
        repoURL: 'https://github.com/lamadome/GlooOps-lamadome2'
        targetRevision: main
        path: teams/bookinfo/{{name}}
      destination:
        name: '{{cluster}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
