name: create-ephemeral-track
description: 'Create an ephemeral track'
inputs:
  app-name:  # id of input
    description: 'name of the argo app'
    required: true
  argo-token:
    description: 'Argo token'
    required: true
  argo-url:
    description: 'Argo url'
    required: true
  type:
    description: 'Type of App or Appset'
    required: true
  revision:
    description: 'Commit SHA of the app'
    required: true
runs:
  using: "composite"
  steps:
    - run:  |
        curl https://$ARGOCD_SERVER/api/v1/applications/${{ inputs.app-name }}/sync \
          -X POST \
          -H "Authorization: Bearer $ARGOCD_AUTH_TOKEN" \
          -H 'Content-Type: application/json' \
          -d '{"revision": "'${{ inputs.revision }}'"}'
      if: ${{ inputs.type == 'app' }}
      env:
          ARGOCD_SERVER: ${{ inputs.argo-url }}
          ARGOCD_AUTH_TOKEN: ${{ inputs.argo-token }}
      shell: bash