apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

patches:
  - target:
      kind: Service
      name: istio-eastwestgateway
    patch: |-
      - op: replace
        path: /metadata/labels/topology.istio.io~1network
        value: cluster2
      - op: replace
        path: /spec/selector/topology.istio.io~1network
        value: cluster2
