apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workspace-settings
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gloo-mesh
  source:
    repoURL: https://github.com/lamadome/GlooOps-lamadome2
    targetRevision: main
    path: teams/platform/workspaces/cluster1
  destination:
    name: cluster1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
