apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-server
spec:
  destination:
    name: 'mgmt'
    namespace: gloo-mesh
  sources:
    - repoURL:  https://github.com/lamadome/GlooOps-lamadome2
      targetRevision: HEAD
      ref: myRepo
    - repoURL: 'https://storage.googleapis.com/gloo-mesh-enterprise/gloo-mesh-enterprise'
      targetRevision: 2.2.6
      chart: gloo-mesh-enterprise
      helm:
        valueFiles:
          - $myRepo/teams/platform/mgmt-server/values.yaml
  project: gloo-mesh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false
