name: download-argo
description: 'Download argo cli'
runs:
  using: "composite"
  steps:
    - run: |  
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        mv argocd-linux-amd64 argocd
      shell: bash