apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fake-service-appset
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - List:
      elements:
      - name: cluster1
        cluster: cluster1
      - name: cluster1-canary
        cluster: cluster1
      - name: cluster2
        cluster: cluster2
      - name: cluster2-canary
        cluster: cluster2
  template:
    metadata:
      name: 'fake-service-{{name}}'
    spec:
      project: fake-service
      source:
        repoURL: 'https://github.com/lamadome/GlooOps-lamadome2'
        targetRevision: main
        path: teams/fake-service/{{name}}
      destination:
        name: '{{cluster}}'
      syncPolicy:
        automated: null
        managedNamespaceMetadata:
          labels:
            istio.io/rev: 1-17
        syncOptions:
        - CreateNamespace=true
