apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../in-cluster/gloo-client-cluster1.yaml
- ../in-cluster/gloo-client-cluster2.yaml
- gloo-cluster1.yaml
- gloo-cluster2.yaml
