apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: payments
  namespace: payments
  labels:
    expose-payments: "true"
spec:
  http:
    - name: payments
      forwardTo:
        destinations:
          - ref:
              name: payments-app
              namespace: payments
            kind: SERVICE
            port:
              number: 8081
