apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: payment
  namespace: payments
  labels:
    expose: "true"
spec:
  hosts:
  - payments.global
  services:
  - namespace: payments
    labels:
      app: payments-app
  ports:
    - number: 8081
      protocol: HTTP
