apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: payments
  namespace: payments
spec:
  importFrom:
  - workspaces:
    - name: gateways
    resources:
    - kind: SERVICE
  exportTo:
  - workspaces:
    - name: gateways
    resources:
    - kind: SERVICE
      labels:
        app: frontend
    - kind: ALL
      labels:
        expose-payments: "true"
