apiVersion: admin.gloo.solo.io/v2
kind: IstioLifecycleManager
metadata:
 name: cluster-installation
 namespace: gloo-mesh
spec:
 installations:
   - clusters:
     - name: <cluster>
       defaultRevision: true
     revision: 1-17
     istioOperatorSpec:
       profile: minimal
       hub: us-docker.pkg.dev/gloo-mesh/istio-workshops
       tag: 1.17.1-solo
       namespace: istio-system
       values:
         global:
           meshID: mesh1
           multiCluster:
             clusterName: <cluster>
           network: <cluster>
       meshConfig:
         accessLogFile: /dev/stdout
         defaultConfig:
           envoyMetricsService:
             address: gloo-mesh-agent.gloo-mesh:9977
           proxyMetadata:
             ISTIO_META_DNS_CAPTURE: "true"
             ISTIO_META_DNS_AUTO_ALLOCATE: "true"
       components:
         pilot:
           k8s:
             env:
               - name: PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES
                 value: "false"
         ingressGateways:
         - name: istio-ingressgateway
           enabled: false
