name: Argo Push
on:
  push:
    branches: [ "main" ]
    paths:
      - teams/fake-service/src/**
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  argo-app-sync:
    runs-on: ubuntu-latest  # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      #- uses: ./.github/actions/install-argo
      - uses: ./.github/actions/argo-sync-app
        with:
          app-name: fake-service-frontend
          argo-token: ${{ secrets.ARGOCD_TOKEN }}
          argo-url: ${{ secrets.ARGOCD_SERVER }}
          type: app
      - uses: ./.github/actions/argo-sync-app
        with:
          app-name: fake-service-backend
          argo-token: ${{ secrets.ARGOCD_TOKEN }}
          argo-url: ${{ secrets.ARGOCD_SERVER }}
          type: app