---
name: Build and Publish fake-service
on:
  push:
    branches: [ "main" , "argo-commit-pinning" ]
    paths:
      - teams/fake-service/src/**
jobs:
  ui:
    env:
      GONOSUMDB: "github.com/moby/moby"
    name: Build UI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Build
        run: |
          cd ./teams/fake-service/src
          make build_ui

      - uses: actions/upload-artifact@v2
        with:
          name: ui
          path: |
            ./teams/fake-service/src/ui/build

  build:
    env:
      GONOSUMDB: "github.com/moby/moby"
      GO111MODULE: "on"
    name: Build Application
    runs-on: ubuntu-latest
    needs: ui
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - uses: actions/download-artifact@v2
        with:
          name: ui
          path: ./teams/fake-service/src/ui/build

      - name: Get dependencies
        run: |
          cd ./teams/fake-service/src
          go get -v -t ./...
      - name: Build
        run: |
          cd ./teams/fake-service/src
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/linux/amd64/fake-service
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o bin/linux/arm64/fake-service
      - uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            ./teams/fake-service/src/bin

  release:
    env:
      GONOSUMDB: "github.com/moby/moby"
    outputs:
      sha: ${{ steps.digest.outputs.digest }}
    name: Release Application
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          name: binaries
          path: ./teams/fake-service/src/bin

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Multi-Arch Builder
        run: |
          cd ./teams/fake-service/src
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multi
          docker buildx use multi
          docker buildx inspect --bootstrap

      - name: Build and push Docker
        run: |
          cd ./teams/fake-service/src
          docker buildx build --platform linux/arm64,linux/amd64 \
            -t lamadome/fake-service:${GITHUB_SHA} \
            -f Dockerfile \
            ./bin \
            --push
          echo "Outputting digest: $GITHUB_SHA"
          echo "sha=$GITHUB_SHA" >> $GITHUB_OUTPUT    

  update-deployment:
    name: Update K8s deployment manifests
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Intall yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq
      - name: Update fake-service Deployment YAML
        run: |
          cd ./teams/fake-service/cluster1-canary
          kustomize edit set image lamadome/fake-service:${GITHUB_SHA}
          cd ../cluster1
          bash kustomize.sh
      - name: Commit back any changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Set image tag to ${GITHUB_SHA}"  || true
          git push
