---
name: Deploy fake-service
on:
  push:
    branches: [ "main" , "argo-commit-pinning" ]
    paths:
    - "teams/fake-service/**"
    - "!teams/fake-service/src/**"
jobs:
  sync-argocd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/argo-sync-app
        name: Sync fake-service-frontend
        with:
          app-name: fake-service-frontend
          argo-token: ${{ secrets.ARGOCD_TOKEN }}
          argo-url: ${{ secrets.ARGOCD_SERVER }}
          type: app
          revision: $GITHUB_SHA
      - uses: ./.github/actions/argo-sync-app
        name: Sync fake-service-backend
        with:
          app-name: fake-service-backend
          argo-token: ${{ secrets.ARGOCD_TOKEN }}
          argo-url: ${{ secrets.ARGOCD_SERVER }}
          type: app
          revision: $GITHUB_SHA
#      - name: notify-argo
#        run: |
#          curl https://${{ secrets.ARGOCD_SERVER }}/api/v1/applications/fake-service-frontend/sync \
#            -X POST \
#            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
#            -H 'Content-Type: application/json' \
#            -d '{"revision": "'$GITHUB_SHA'"}'
#          curl https://${{ secrets.ARGOCD_SERVER }}/api/v1/applications/fake-service-backend/sync \
#            -X POST \
#            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
#            -H 'Content-Type: application/json' \
#            -d '{"revision": "'$GITHUB_SHA'"}'