---
name: Deploy fake-service
on:
  push:
    paths:
    - "teams/fake-service/**/*.?(yml|yaml)"
    - "!teams/fake-service/src/**"

jobs:
  sync-argocd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: notify-argo
        run: |
          curl https://${{ secrets.ARGOCD_SERVER }}/api/v1/applications/fake-service-appset/sync \
            -X POST \
            -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
            -H 'Content-Type: application/json' \
            -d '{"revision": "$GITHUB_SHA", "dryRun": "true"}'