---
name: Deploy fake-service
on:
  push:
    branches: [ "main" , "argo-commit-pinning" ]
    paths:
    - "teams/fake-service/**"
    - "!teams/fake-service/src/**"
jobs:
  sync-argocd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/argo-sync-app
        name: Sync fake-service-cluster1
        with:
          app-name: fake-service-cluster1
          argo-token: ${{ secrets.ARGOCD_TOKEN }}
          argo-url: ${{ secrets.ARGOCD_SERVER }}
          type: app
          revision: $GITHUB_SHA
      - uses: ./.github/actions/argo-sync-app
        name: Sync fake-service-cluster1-canary
        with:
          app-name: fake-service-cluster1-canary
          argo-token: ${{ secrets.ARGOCD_TOKEN }}
          argo-url: ${{ secrets.ARGOCD_SERVER }}
          type: app
          revision: $GITHUB_SHA      
      - uses: ./.github/actions/argo-sync-app
        name: Sync fake-service-cluster2
        with:
          app-name: fake-service-cluster2
          argo-token: ${{ secrets.ARGOCD_TOKEN }}
          argo-url: ${{ secrets.ARGOCD_SERVER }}
          type: app
          revision: $GITHUB_SHA
      - uses: ./.github/actions/argo-sync-app
        name: Sync fake-service-cluster2-canary
        with:
          app-name: fake-service-cluster2-canary
          argo-token: ${{ secrets.ARGOCD_TOKEN }}
          argo-url: ${{ secrets.ARGOCD_SERVER }}
          type: app
          revision: $GITHUB_SHA